language: swift
jobs:
  include:
    - os: linux
      dist: bionic
      language: generic
    - os: osx
      osx_image: xcode11.3
      language: swift
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - make runCI
